kind: Service
apiVersion: v1
metadata:
  name: telepresence-example-svc
  labels:
    app: telepresence-example
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: telepresence-example-app
